version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    networks:
      - esnet
    mem_limit: 1g

  kibana:
    image: kibana:8.12.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - esnet    
    depends_on:
      - elasticsearch

  backendgw:
    build:
      context: .
      dockerfile: src/Gateways/BackendGateway/Dockerfile
    ports:
      - "5111:8080"
    networks:
      - esnet
    depends_on:
      - mongo
      - identity

  identity:
    build:
      context: .
      dockerfile: src/Microservices/Identity.Microservice/Dockerfile
    ports:
      - "5025:8080"
    networks:
      - esnet
    depends_on:
      - mongo

  books:
    build:
      context: .
      dockerfile: src/Microservices/Books.Microservice/Dockerfile
    ports:
      - "5130:8080"
    networks:
      - esnet
    depends_on:
      - mongo
      - identity

  orders:
    build:
      context: .
      dockerfile: src/Microservices/Orders.Microservice/Dockerfile
    ports:
      - "5019:8080"
    networks:
      - esnet
    depends_on:
      - mongo
      - identity

volumes:
  esdata1:
    driver: local
  mongodata:
    driver: local

networks:
  esnet:
    name: esnet
    driver: bridge