services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backendgw:
  build:
    context: .
    dockerfile: src/Gateways/BackendGateway/Dockerfile
  ports:
    - 5111:80
  depends_on:
    - mongo
    - identity

  identity:
    build:
      context: .
      dockerfile: src/Microservices/Identity.Microservice/Dockerfile
    ports:
      - 5025:80
    depends_on:
      - mongo

  books:
    build:
      context: .
      dockerfile: src/Microservices/Books.Microservice/Dockerfile
    ports:
      - 5130:80
    depends_on:
      - mongo
      - identity

  orders:
    build:
      context: .
      dockerfile: src/Microservices/Orders.Microservice/Dockerfile
    ports:
      - 5019:80
    depends_on:
      - mongo
      - identity