version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - esnet

  backendgw:
    build:
      context: .
      dockerfile: src/Gateways/BackendGateway/Dockerfile
    ports:
      - "5111:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - esnet
    depends_on:
      - mongo
      - identity

  identity:
    build:
      context: .
      dockerfile: src/Microservices/Identity.Microservice/Dockerfile
    ports:
      - "5025:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - esnet
    depends_on:
      - mongo

  books:
    build:
      context: .
      dockerfile: src/Microservices/Books.Microservice/Dockerfile
    ports:
      - "5130:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - esnet
    depends_on:
      - mongo
      - identity

  orders:
    build:
      context: .
      dockerfile: src/Microservices/Orders.Microservice/Dockerfile
    ports:
      - "5019:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - esnet
    depends_on:
      - mongo
      - identity

networks:
  esnet:
    name: esnet
    driver: bridge