POST {{host}}/books
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "authorId": "65aa39d01d1692c54fabae02",
    "title": "Crime and punishment",
    "description": "cool book, i should finish it"
}